# fly.toml app configuration file generated for bacar-skybridge-14 on 2026-08-19T13:12:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bacar-skybridge-14'
primary_region = 'jnb'
kill_timeout = '60s'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
